spring.application.name=ReactiveLibrary
spring.r2dbc.url=r2dbc:mysql://localhost:3306/reactivelibrary
spring.r2dbc.username=root
spring.r2dbc.password=
spring.sql.init.platform=mysql
spring.sql.init.mode=always
server.port=8097
spring.sql.init.schema-locations=classpath:schema.sql
